# **Pytorch Tutorial**

## **Basic Handling**

In [1]:
import torch

### **다양한 타입의 텐서**

In [9]:
ft = torch.FloatTensor([[1,2],
                       [3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [10]:
lt = torch.LongTensor([[1,2],
                       [3,4]])

In [42]:
bt = torch.ByteTensor([[1,2],
                       [3,4]])
bt

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

임의의 값으로 채워진 원하는 크기의 텐서를 만들 수도 있다.

In [43]:
tensor = torch.FloatTensor(3,2)
tensor

tensor([[-1.5287e-36,  7.6371e-43],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

---

### **넘파이 호환**

In [17]:
import numpy as np

In [18]:
x = np.array([[1,2],
              [3,4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [19]:
# numpy ndarray -> torch tensor
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [20]:
# torch tensor -> numpy ndarray
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


---

### **텐서 타입 변환**

In [26]:
ft = torch.FloatTensor([[1,2],
                         [3,4]])
ftToLt = ft.long()
ltToFt = ftToLt.float()
print(ft)
print(ftToLt)
print(ltToFt)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]])


---

### **텐서 크기 구하기**

In [28]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])

(1) 텐서 크기를 구하려면 size() 함수를 호출하거나, shape 속성에 접근한다.
두 방법의 차이는 없고 size() 함수의 결괏값이 shape 속성에 담겨있다고 보면 된다.

In [30]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


(2) 특정 차원의 크기를 알기 위해서는 size()함수에 인자에 원하는 차원의 인덱스를 넣거나, shape 속성의 해당 차원 인덱스에 접근한다.

In [33]:
print(x.size(0)) # 0차원의 크기
print(x.size(1)) # 1차원의 크기

print(x.shape[2]) # 2차원의 크기
print(x.shape[-1]) # 2차원의 크기

3
2
2
2


(3) 텐서가 몇 차원인지 알기 위해서는 dim() 함수를 활용한다. 이것은 shape 속성의 배열 크기와 같다.

In [34]:
print(x.dim())
print(len(x.size()))

3
3


---

### **요소별 산술 연산**

(1) 행렬합, 행렬차, 행렬곱, 행렬 나눗셈

In [35]:
a = torch.FloatTensor([[1,2],
                       [3,4]])
b = torch.FloatTensor([[2,2],
                       [3,3]])

In [36]:
a+b

tensor([[3., 4.],
        [6., 7.]])

In [37]:
a-b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [38]:
a*b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [39]:
a/b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

(2) 논리 연산

In [40]:
a == b

tensor([[False,  True],
        [ True, False]])

In [41]:
a != b

tensor([[ True, False],
        [False,  True]])

---

### **인플레이스 연산**

---

### **차원 축소 연산: 합과 평균**

---

### **브로드캐스트 연산**

---

## **텐서 형태 변환**

### **View 함수**

---

### **Squeeze 함수**

---

### **Unsqueeze 함수**

---

## **텐서 자르기&붙이기**

### **인덱싱과 슬라이싱**

---

### **Split 함수**

---

### **Chunk 함수**

---

### **Index Select 함수**

---

### **Concatenate 함수**

---

### **Stack 함수**

---

## **유용한 함수들**